tests/pytests/.editorconfig
Can be used with any editor (assuming the plugin is available) to
configure code style. Can also be used to lint.
Indent style and size were extrapolated from existing code.
PEP8 mandates final newlines.
Trailing whitespace is just a nuisance.
Line length is the default that PyCharm suggested.
=> Add EditorConfig settings

pyuvm/__init__.py, pyuvm/s18_register_model.py, tests/pytests/test_18_register_model.py
Add support for foundational UVM register layer classes: `uvm_reg_block`, `uvm_reg_map`, `uvm_reg` and `uvm_reg_field`.
=> Add foundational register model classes

.editorconfig, cleanall.mk, examples/TinyALU/Makefile, pyuvm/s06_reporting_classes.py, setup.py, tests/cocotb_tests/config_db/Makefile, tests/cocotb_tests/queue/Makefile, tests/cocotb_tests/run_phase/Makefile, tests/cocotb_tests/t08_factories/Makefile, tests/cocotb_tests/t09_phasing/Makefile, tests/cocotb_tests/t12_tlm/Makefile, tests/cocotb_tests/t13_components/Makefile
Logging to `sys.stdout` creates consistent behavior across all simulators.
=> Now log to sys.stdout instead of sys.stderr

examples/TinyALU/.gitignore, examples/TinyALU/tinyalu_cocotb.py, examples/TinyALU/tinyalu_uvm.py
Was seeing this:
pyuvm/examples/TinyALU/tinyalu_cocotb.py:69:
DeprecationWarning: Setting values on handles
using the ``dut.handle = value`` syntax is deprecated.
Instead use the ``handle.value = value`` syntax
Also get rid of discouraged glob import style.
According to PEP8, "Wildcard imports ... should be avoided".
=> Fix DeprecationWarning

pyuvm/s08_factory_classes.py
The intent here is to concatenate these two adjacent strings,
but the way it's written the second string piece is thrown away by the
interpreter.
=> Fix string statement has no effect bugs

pyuvm/s06_reporting_classes.py
Resolved the issue of adding variables to the `uvm_report_object` namespace.
=> Now using a protected variable for default logging level

pyuvm/s12_uvm_tlm_interfaces.py
My analysis components stopped working after the recent update.
`0ccf4ae` restructured port and export base classes, and removed connect()
from uvm_analysis_port. That needs to work differently to maintain the
subscribers list.
This is a quick fix but I think more needs to be done here:
`uvm_port_base` creates attribute `export` which only applies to the single-producer, single-consumer style ports. It looks like the class structure should be refactored some more so that analysis ports/exports don't inherit from a class that includes these single-consumer-specific features.
I am less sure about what should happen with `provided_to` and `connected_to`; at the moment nothing seems to use these.
Also I should probably figure out how pyuvm's regression tests work, and update them if I find …
=> make analysis ports work again after class restructure

pyuvm/s09_phasing.py, pyuvm/utility_classes.py
fork() is deprecated, also it causes a simulator crash if a forked
coroutine raises an exception before await-ing.
See https://github.com/cocotb/cocotb/issues/2804
=> phasing: replace fork() with start_soon()

pyuvm/s13_uvm_component.py, pyuvm/utility_classes.py, tests/cocotb_tests/run_phase/test.py
Test cases and fixes for a couple of objection issues.
The main one being that a crashing test would leave raised objections, causing a following test to never end.
I added a "test" to see if a warning is printed, but it doesn't actually test if the warning gets printed - I don't know how to do that. It needs some kind of mocking of the logger, I guess.
=> Objection fixes

pyuvm/s14_15_python_sequences.py
A minor modification for your consideration:
Print a more helpful error using an assertion if a driver tries to
get_next_item before it has been connected to an export.
Do this in a try/except block to avoid the cost of checking every time.
Changes this:
```
AttributeError: 'NoneType' object has no attribute 'get_next_item'
```
into this:
```
AssertionError: export is not connected
```
=> More helpful error when port is not connected

examples/TinyALU/testbench.py, examples/TinyALU/tinyalu_utils.py
The example `Scoreboard` was not reporting errors to **cocotb***
=> Fixed error in example. Fixes #80

examples/TinyALU/testbench.py, pyuvm/s05_base_classes.py, pyuvm/s09_phasing.py, pyuvm/s13_uvm_component.py, setup.py, tests/cocotb_tests/t08_factories/factory_tests.py, tests/pytests/test_05_base_classes.py
* fixed do_copy() and clone()
* run_test sets default log level to INFO
* Now you can turn on phase logging
* Fixed bug in uvm_root() when clearing singletons
* Fixed example to demonstrate errors
=> 2.6.1 release

.github/workflows/main.yml, examples/TinyALU/Makefile, examples/TinyALU/hdl/vhdl/tinyalu.vhd, examples/TinyALU/testbench.py, pyuvm/s05_base_classes.py, pyuvm/s09_phasing.py, pyuvm/s13_uvm_component.py, pyuvm/utility_classes.py, setup.py, tests/cocotb_tests/run_phase/test.py, tests/cocotb_tests/t08_factories/factory_tests.py, tests/pytests/test_05_base_classes.py, tox.ini
Fix #87 
`drop_objection()` assumed that each instance of a component would only call `raise_objection()`/`drop_objection()` once.  But if you awaited `super.run_phase()` the first call to `drop_objection()` would end run phase.
=> Nested drop_objection() in same object existed early

pyuvm/extension_classes.py
The stage variable on the test decorator defaults to None, which is broken and we are changing it upstream. But until that percolates the default here will have to stay `None` to prevent issues when `cocotb.test` and `pyuvm.test` are used in the same module and the stages on each are `None` and `0`, which fail to compare.
=> Fix issue with stage on test decorator

examples/TinyALU/testbench.py, tests/cocotb_tests/t12_tlm/test.py
Now we want 
```
import cocotb
import pyuvm
```
At the top even if we import other resources directly.
This gives us
```
@pyuvm.test()
```
Which is clearer than just `@test()`
=> Tweeked example to import pyuvm

pyuvm/s14_15_python_sequences.py
Added missing underscore in ResponseQueue.__str__()
=> Fix typo in ResponseQueue.__str__()

pyuvm/s12_uvm_tlm_interfaces.py, pyuvm/utility_classes.py
Adds possibility to call TLM methods directly with FIFOs.
```python
self.my_fifo = uvm_tlm_analysis_fifo("my_fifo", self)
item = await self.my_fifo.get()
```
Tests probably need updating but I cannot run them in my environment.
Closes #107
=> Add TLM methods to uvm_tlm_fifo_base

README.md, examples/TinyALU/testbench.py, pyuvm/extension_classes.py
Closes #109. This PR changes how the `pyuvm.test` decorator works so that it returns the test object rather than the test class. This has two effects:
1. test can now be specified using TESTCASE
2. inheriting from decorated test now requires getting the `class_` attribute from the parent test object
Some effort was put into trying to alleviate point 2, but it does not seem this is possible in Python with the current cocotb RegressionManager implementation.
=> Change how pyuvm.test decorator works

pyuvm/extension_classes.py
The `stage` variable was changed in 1.7. This version condition allows the existing value to work for version both before and after 1.7.
=> Fix test decorator to work with cocotb 1.7

pyuvm/utility_classes.py, tests/cocotb_tests/run_phase/test.py
Fix #112, bug where `run_phase` could end before all objections were dropped from all components.  Also added a new test to protect functionality.  Confirmed test fails without the fix and passes with it.
=> Fix #112, run_phase now waits for objections from all components

examples/TinyALU/Makefile
cocotb documentation makes a distinction between Makefile variables and environment variables. The former are used in cocotb Makefiles while the latter are read in the Python code as environment variables. The latter types need the Make directive `export` to make them environment variables. What makes it confusing is that a few of the environment variables are already either exported or passed as command-line parameters by cocotb, like `MODULE`, but the rest need to be exported by the user.
`COCOTB_REDUCED_LOG_FMT` is one of those that need the `export` directive so I added it. Also, only integer values are accepted for it, so I changed its value from `True` to `1`. The default value is 1 so functionally this PR changes nothing.
=> Fix environment variable definition in TinyALU Makefile

pyuvm/s06_reporting_classes.py, tox.ini
pyuvm colored output can not be disabled as it always uses the _SimColourLogFormatter_
For post-processing of log files normally is desirable to have a plain log file without colors. For this purpose cocotb provides the COCOTB_ANSI_OUTPUT Environment variable.
Fix adds support for the COCOTB_ANSI_OUTPUT Environment variable to pyuvm logging.
=> Fix colored output when COCOTB_ANSI_OUTPUT is set 0

pyuvm/s06_reporting_classes.py
Exception occurs when passing non-strings to the logger, this should let it print whatever comes in (as long as it has a string representation).
=> Automatic string conversion for log messages

Makefile, examples/TinyALU/Makefile, examples/TinyALU/hdl/verilog/tinyalu.sv
Indentation change in TinayALU
Tried TinayALU with **Verilator 5.006 2023-01-22 rev v5.006** and **cocotb-1.8.0.dev0**.  The change to TinayALU fixes ventilator errors related to width mismatch.
=> Update example TinyALY to work with Verilator 5

examples/TinyALU/testbench.py
fork has been deprecated from cocotb 1.7.0
(https://github.com/cocotb/cocotb/issues/2663)
This PR resolves https://github.com/pyuvm/pyuvm/issues/128
=> Replace fork with start_soon in example

.github/workflows/main.yml
as we have flake8 fixes coming in, Lets enable CI on `ral_dev` to make sure tests pass on CI before merge
=> Enable CI for ral_dev

examples/TinyALU_reg/hdl/verilog/TinyALUreg.sv, examples/TinyALU_reg/hdl/verilog/tinyalu.sv
Generate a passthrough interface instead of APB for easy testing of RAL
generate command:
```
peakrdl regblock ../../TinyALUreg.rdl -o ./ --cpuif passthrough --hwif-report
```
=> Generate passthrough interface

pyuvm/s13_uvm_component.py
Adding this method allows users to raise objections using `with`, meaning that on any break from the loop, the objection will always be dropped.
Example usage:
```py
async def run_phase(self):
with self.objection():
print("run phase started")
assert False
```
This also saves users from needing to debug a missing drop_objection, similar to Python's file opening and closing system.
=> Add Pythonic method for raising and dropping objections

pyuvm/_utils.py, pyuvm/extension_classes.py, pyuvm/s06_reporting_classes.py, pyuvm/s13_uvm_component.py, tests/cocotb_tests/ext_classes/test.py, tox.ini
* `cocotb.log` module was renamed to `cocotb.logging` module to prevent shadowing the `cocotb.log` variable.
* `cocotb.test` now works in a different way so we don't have to put the Test object into the module. This should also make `TESTCASE` work correctly.
=> Fix issues with current 2.0 support

examples/TinyALU/testbench.py, examples/TinyALU_reg/testbench.py
as this will be deprecated in cocotb 2.0, see cocotb commit 579bfa682cf9ec76646654fc8c7544d812c0cfc1
Fixes #232
=> Await task directly, instead of await'ing Join

pyuvm/s19_uvm_reg_field.py, pyuvm/s20_uvm_reg.py, tests/pytests/test_uvm_ral.py, tests/pytests/test_uvm_reg_block.py, tests/pytests/test_uvm_reg_map.py
Hello. I ran into a problem when using the automatic predictor in uvm_reg.  So, for example, I have a SCR__CTRL register containing two fields ARM [0] [RW] and RESERVED [31:1][RO]. When using uvm_reg.predict (0xFFFFFFFF, access_e.UVM_WRITE), I expect to get the value 0x1 from reg.get_mirrored_value(), but I get 0xFFFFFFFF. The problem is that an value is passed for each field in the register and for RW/WO it is not trimmed to the size of the field.  When predicting the ARM field, in its field.get_value we get 0xFFFF_FFFF, but we should get 0x1, since the field is one-bit. This received value overwrites the upper reserved bits [31:1] when calling reg.get_mirrored_value()
Here is an example of a verification scenario:
```
from pyuvm import *
import logging
import cocotb
class SCR__CTRL …
```
=> fix: predicton in uvm_reg_field

pyuvm/s19_uvm_reg_field.py, pyuvm/s20_uvm_reg.py, pyuvm/s21_uvm_reg_map.py
I ran into these problems when trying to read values from registers and logging the field names with the values. 
`uvm_reg_field` uses `self._name` as a duplicate of `uvm_object`'s `._obj_name`. This is changed to use `self.get_name()` method that every `uvm_object` has.
The method `self.get_full_name()` in `uvm_field_reg` called `self._parent` which produces the following error:
```bash
File "~/.venv/lib/python3.12/site-packages/pyuvm/s19_uvm_reg_field.py", line 125, in get_full_name
return self._parent + "." + self._name
~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'cl_dprio_reg' and 'str'
```
To fix this the `get_full_name()` method of the parent is called and the `get_name` method of the field.
`uvm_reg_map` also had a duplicate property `.name`, this was removed …
=> Updated register base classes to use the uvm_object name properies and name methods instead of duplicates.

pyuvm/s06_reporting_classes.py, pyuvm/s14_15_python_sequences.py, tests/cocotb_tests/t14_15_sequences/test_14_15_python_sequences.py
An improvement of the uvm_sequences by adding the `pre_body()` and `post_body()` functions, the implementation is based on the implementation in UVM.  As I have found that I'm missing the functionality given by the pre and post body of the sequences. Especially, when creating larger testbenches and multiple sequences to reduce the amount of repeated code across sequences. 
The implementation will automatically invoke the `pre_body()` before the `body()` and the `post_body()` after it. The implementation does not affect the behavior of sequences as is unless they are extended by the user.  The implementation has been done as close to the original UVM implementation as possible, see code below. 
The original UVM implementation :
```
if (call_pre_post == 1) begin
m_sequence_state = …
```
=> Implement pre_body and post_body for sequences

.github/workflows/main.yml, .gitignore, Makefile, pyuvm/s18_uvm_reg_block.py, pyuvm/s19_uvm_reg_field.py, pyuvm/s20_uvm_reg.py, pyuvm/s24_uvm_reg_includes.py, tox.ini
The latest version of python 3.13 had upgrades that caused flake8 errors. We were creating python code in fstrings that was not flake8 compliant. These were ignored in the past, but flake8 catches them when running with the latest versions of python.
Also, for some reason, I was not using ubuntu-latest. That is fixed now.
=> Updated to latest versions of python

examples/TinyALU_reg/testbench.py, examples/TinyALU_reg/tinyalu_utils.py, pyuvm/s14_15_python_sequences.py, pyuvm/utility_classes.py, scratch/dut_cocotb.py, tests/cocotb_tests/config_db/test.py, tests/cocotb_tests/ext_classes/test_ext_classes.py, tests/cocotb_tests/queue/test.py, tests/cocotb_tests/run_phase/test.py, tests/cocotb_tests/t12_tlm/test_12_uvm_tlm_interfaces.py, tests/cocotb_tests/t13_components/test.py, tests/cocotb_tests/t14_15_sequences/test.py, tests/cocotb_tests/t14_15_sequences/test_14_15_python_sequences.py
This fixes all code causing a DeprecationWarning in 2.0 while still supporting 1.x
* `units` was renamed to `unit`
* `LogicArray.integer` was deprecated
* `Event` doesn't take a name anymore (to match asyncio)
=> Fix deprecations warnings from 2.0

pyuvm/s18_uvm_reg_block.py, tests/pytests/test_uvm_reg_block.py
Changes:
- Added the method `get_field_by_name()`, based on the specification "IEEE Standard for Universal Verification Methodology Language Reference Manual (Revision of IEEE Std 1800.2-2017)". A comment with the corresponding section number has been added.
- Rewrote the method `get_reg_by_name()` according to the UVM specification. A comment with the corresponding section number has been added.
- Added tests for `get_field_by_name()` and `get_reg_by_name()`:
- test_reg_block_get_reg_by_name()
- test_reg_block_get_field_by_name()
=> Improvement of get_by_name methods in uvm_reg_block

pyuvm/s13_predefined_component_classes.py
Convert the comments from the SystemVerilog source code into a Python docstring format.
=> Add docstrings to uvm classes and methods
