- .github/workflows/main.yml
Add some basic Github Actions CI check.
Also flake8 that fails at the moment.
Example: https://github.com/themperek/pyuvm/actions/runs/862989949
> Add Github Actions integration

- examples/TinyALU/hdl/verilog/tinyalu.sv
This blocking assignment looks like a typo.
> Change from blocking to non-blocking operator

- pyuvm/s05_base_classes.py
- pyuvm/s06_reporting_classes.py
- tests/pytests/test_05_base_classes.py
I added the ability to set default logging level with a class
method on uvm_report_object.
I now force users to use the copy module to make copies.
> Default logging and force deepcopy

- pyuvm/s06_reporting_classes.py
- pyuvm/s12_uvm_tlm_interfaces.py
- pyuvm/s14_15_python_sequences.py
Refactored `uvm_export_base` and `uvm_port_base` to fix issues @jonpodor found.
> Refactored port and export

- README.md
- setup.py
Now with comments in README.md for 2.5a
> Updated README.md for 2.5a

- README.md
- examples/TinyALU/testbench.py
- examples/TinyALU/tinyalu_utils.py
Fixed the example and the README.md for the new "clean singleton" run model
> Refactored example for clean singletons

- pyuvm/s13_predefined_component_classes.py
- pyuvm/s14_15_python_sequences.py
> give uvm_sequence a default name

- .github/workflows/main.yml
- examples/TinyALU/Makefile
- examples/TinyALU/hdl/vhdl/tinyalu.vhd
- tox.ini
> Add VHDL/GHDL example to CI

- pyuvm/extension_classes.py
Should fix the issue mentioned [here](https://gitter.im/cocotb/Lobby?at=6343f355773e7e5c7bcaa167).
> Fix test decorator to work with cocotb 1.7

- tox.ini
Details at: 
https://github.com/pyuvm/pyuvm/issues/122
> Minor edit to tox.ini to support Python 3.6/3.9

- tox.ini
As per https://github.com/pyuvm/pyuvm/pull/129
> Adding waiver for W503

- pyuvm/s06_reporting_classes.py
> Replace logger name with pathname+lineno in logging messages

- pyuvm/s05_base_classes.py
- tests/cocotb_tests/t05_base_classes/Makefile
- tests/cocotb_tests/t05_base_classes/clk.sv
- tests/cocotb_tests/t05_base_classes/test.py
- tests/pytests/test_05_base_classes.py
- tox.ini
Added support for simulation time in `uvm_transaction` as suggested in https://github.com/pyuvm/pyuvm/issues/72
> Add support for uvm_transaction simulation time recording

- pyuvm/__init__.py
- pyuvm/s17_register_enumerations.py
- tests/pytests/test_17_register_enumerations.py
- Implemented `uvm_hdl_path_slice` and `uvm_hdl_path_concat`
- Declared most of the enums required for RAL implementation
> Add implementation for chapter 17

- pyuvm/s18_register_model.py
- tests/pytests/test_18_register_model.py
Update `uvm_reg_map`  implementation with most of the methods needed for RAL
> Update uvm_reg_map implementation

- scratch/dut_cocotb.py
- tests/cocotb_tests/config_db/test.py
- tests/cocotb_tests/queue/test.py
- tests/cocotb_tests/t12_tlm/test_12_uvm_tlm_interfaces.py
- tests/cocotb_tests/t13_components/test.py
- tests/cocotb_tests/t14_15_sequences/test.py
Fix Issue pyuvm#160 by Replacing all the instances of cocotb.fork() to cocotb.start_soon() in all tests
> Fix pyuvm#160, replace all cocotb.fork() with cocotb.start_soon() in all tests

- Makefile
Fixes Typo Mentioned in Issue pyuvm#121
> Fix Typo mentioned in pyuvm#121

- pyuvm/s13_uvm_component.py
Implements changes discussed in #177.
> Add default argument to ConfigDB().get()

- requirements.txt
I don't want to risk breaking at 2.0
> limit cocotb to 1.8+

- requirements.txt
- tests/cocotb_tests/decorator/Makefile
- tests/cocotb_tests/decorator/clk.sv
- tests/cocotb_tests/decorator/test_decorator.py
- tox.ini
You can now keep all singletons or a set of singletons.  This closes issue #96
> Now pyuvm.test() allows users to keep singletons

- README.md
- docs/docsources/UVM_and_Python.rst
Suggested edits to address minor issues that I noticed while reading the documentation.
> Minor documentation edits and typo fix

- pyuvm/s20_uvm_reg.py
@raysalemi  Hello!)  This MR repairs the CI. In my edits I violated the flake8 standard
> fix: flake8 in s20_uvm_reg.py

- pyuvm/s06_reporting_classes.py
> fix: name duplication in PyuvmFormatter

- examples/TinyALU/testbench.py
- examples/TinyALU_reg/testbench.py
- pyuvm/extension_classes.py
- pyuvm/utility_classes.py
- tests/cocotb_tests/decorator/test_decorator.py
Closes #241. The 2.0 beta will release soon and we are in a feature/change freeze until the release.
> Make changes for 2.0 compatability

- examples/TinyALU/hdl/vhdl/tinyalu.vhd
- examples/TinyALU/tinyalu_utils.py
Moved clock to cocotb except for VHDL.
> Og towards cocotb 2.0

- .pre-commit-config.yaml
- README.md
- examples/TinyALU_reg/testbench.py
- pyproject.toml
- pyuvm/s17_uvm_reg_enumerations.py
- pyuvm/s18_uvm_reg_block.py
- pyuvm/s19_uvm_reg_field.py
- pyuvm/s20_uvm_reg.py
- pyuvm/s21_uvm_reg_map.py
- pyuvm/s24_uvm_reg_includes.py
- pyuvm/s25_uvm_adapter.py
- pyuvm/utility_classes.py
- scratch/dut.sv
- tests/cocotb_tests/t08_factories/factory_tests.py
- tests/cocotb_tests/t14_15_sequences/test_14_15_python_sequences.py
- tests/pytests/test_uvm_ral.py
- tests/pytests/test_uvm_reg.py
- tests/pytests/test_uvm_reg_block.py
- tests/pytests/test_uvm_reg_field.py
- tests/pytests/test_uvm_reg_map.py
Also fixes several spelling mistakes. I'll need to look at the automated fixes to ensure that it didn't do anything weird.
> Add codespell check to pre-commit
